# Generated by Django 4.1.7 on 2023-05-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('chat', '0001_initial'),
	]

	operations = [
		migrations.AlterField(
			model_name='message',
			name='date_created',
			field=models.DateTimeField(auto_now_add=True, null=True),
		),
	]
