# Generated by Django 4.1.7 on 2023-02-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
