# Generated by Django 4.1.7 on 2023-05-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('request', '0002_request_building_request_description_request_square'),
	]

	operations = [
		migrations.AlterField(
			model_name='request',
			name='building',
			field=models.CharField(blank=True, max_length=1, null=True),
		),
	]
