# Generated by Django 4.1.7 on 2023-04-03 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_baseuser_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseuser',
            old_name='is_staff',
            new_name='is_just_admin',
        ),
    ]
