# Generated by Django 4.1.7 on 2023-05-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('user', '0004_rename_is_staff_baseuser_is_just_admin'),
	]

	operations = [
		migrations.AddField(
			model_name='baseuser',
			name='phone_number',
			field=models.CharField(default='0787349428', max_length=14),
		),
	]
