# Generated by Django 4.1.7 on 2023-05-26 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		('user', '0005_baseuser_phone_number'),
	]

	operations = [
		migrations.AlterField(
			model_name='baseuser',
			name='is_active',
			field=models.BooleanField(default=True),
		),
	]
